config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               user_index GET    /user/index(.:format)          user#index
#              admin_index GET    /admin/index(.:format)         admin#index
#           calendar_index GET    /calendar/index(.:format)      calendar#index
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session GET    /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  users/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) users/passwords#edit
#            user_password PATCH  /users/password(.:format)      users/passwords#update
#                          PUT    /users/password(.:format)      users/passwords#update
#                          POST   /users/password(.:format)      users/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                    users GET    /users(.:format)               users#index
#                          POST   /users(.:format)               users#create
#                 new_user GET    /users/new(.:format)           users#new
#                edit_user GET    /users/:id/edit(.:format)      users#edit
#                     user GET    /users/:id(.:format)           users#show
#                          PATCH  /users/:id(.:format)           users#update
#                          PUT    /users/:id(.:format)           users#update
#                          DELETE /users/:id(.:format)           users#destroy
#                     root GET    /                              users#index
#                 calendar GET    /calendar(.:format)            admin#index

Rails.application.routes.draw do
  get 'user/index'

  get 'admin/index'

  get 'calendar/index'

  devise_scope :user do
    get "/users/edit", to: "users/registrations#edit", as: "edit_user_registration"
    put "/users", to: "users/registrations#update", as: "user_registration"
    # get "/users/cancel", to: "users/registrations#cancel", as: "cancel_user_registration"
    get "/sign_in" => "users/sessions#new"
    get '/users/sign_out' => 'users/sessions#destroy'
    delete "/users", to: "users/registrations#destroy"

    get "check_username", to: "users/sessions#check_username"
    get "check_email", to: "users/sessions#check_email"
    get "check_email_registration", to: "users/sessions#check_email_registration"
    post "/users/new" => "users#new", as: "new_users"
    post "/change_role" => "users#change_role", as: "user_change_role"
    post "/suspend/:id" => "users#suspend", as: "user_suspend"
    post "/reactivate/:id" => "users#reactivate", as: "user_reactivate"
    post "/check_user_email" => "users#check_user_email", as: "check_user_email"
    post "/check_user_name" => "users#check_user_name", as: "check_user_name"
    get "/inactive_status" => "users#inactive_status", as: "inactive_status"
  end
  # devise_for :users, skip: :registration
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }, skip: :registration
  resources :users

  root :to => 'events#summary'

  get "/calendar" => "events#calendar"

  post "/create_event" => "events#create", as: "create_events"
  get "/get_event" => "events#get", as: "get_events"
  post "/update_event" => "events#update", as: "update_events"
  get "/events" => "events#index", as: "events"
  post "/events" => "events#index", as: "events_sort"
  post "/change" => "events#change", as: "change_events"
  get "/events/:event_id" => "events#edit", as: "edit_events"
  delete "/delete_event" => "events#destroy", as: "delete_events"
  # get "/myevents" => "events#my_events", as: "my_events"
  post "/comment" => "events#comment", as: "comment_events"
  get "/events/user_events/:user_id" => "events#user_events", as: "user_events"
  post "/events/user_events/:user_id" => "events#user_events", as: "user_events_sort"

  get "/report" => "events#report", as: "report"
  get "/report_filter" => "events#report_filter", as: "report_filter"
  post "/summary_filter" => "events#summary_filter", as: "summary_filter"
  resources :categories
  
  resources :shifts
  get "/shifts/view" => "shifts#show", as: "view_shift"
  
  resources :lunchtimes
  get "/lunchtimes/view" => "lunchtimes#show", as: "view_lunchtime"

  resources :points do
    get :history, on: :collection
  end
  
  
  resources :penalties

  get "/penalties_summary" => "penalties#summary", as: "penalties_summary"
  get "/penalties/user/:user_id" => "penalties#user", as: "penalties_user"
  get "/penalties/your-penalties" => "penalties#show", as: "show"

  resources :consequences

  post "/penalties/confirmed" => "penalties#confirm_penalty", as: "confirm_penalty"
  get "/help" => "helps#index", as: "help"
  resources :holidays
  resources :holidaytypes
  resources :roles
  resources :departments do
    get :show_users, on: :collection
  end
  post "/call_sub" => "departments#call_sub", as: "call_sub"
end

app/models/holiday.rb
# == Schema Information
#
# Table name: holidays
#
#  id             :bigint           not null, primary key
#  holiday_date   :datetime
#  name           :string
#  slug           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  holidaytype_id :integer
#
# Indexes
#
#  index_holidays_on_slug  (slug) UNIQUE
#

class Holiday < ApplicationRecord
  belongs_to :holidaytype
  validates_uniqueness_of :name
  extend FriendlyId
  friendly_id :name, use: :slugged

  
end

app/models/holidaytype.rb
# == Schema Information
#
# Table name: holidaytypes
#
#  id         :bigint           not null, primary key
#  duration   :string
#  end_time   :string
#  hours_off  :integer
#  name       :string
#  slug       :string
#  start_time :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_holidaytypes_on_slug  (slug) UNIQUE
#

class Holidaytype < ApplicationRecord
  has_many :holidays, dependent: :destroy
  validates_uniqueness_of :name
  extend FriendlyId
  friendly_id :name, use: :slugged
  def full_info
    return "#{self.name} - #{self.hours_off}hours (#{self.start_time} - #{self.end_time})"
  end
  def time_info
    return "#{self.start_time} - #{self.end_time}"
  end

  def full_time_info
    return "#{self.name} - #{self.hours_off}hours (#{Dates.time_12(self.start_time, self.end_time)})"
  end
  
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :authenticate_user!, except: []
  layout "index"
  
  before_action :check_active_status
  before_action :check_permission
   
  def check_permission
    redirect_to root_path unless current_user.admin? || current_user.holiday_perm?
  end

  def check_active_status
    redirect_to inactive_status_path if current_user.inactive?
  end

  def index
    @holiday = Holiday.new
    @holidays = Holiday.all.order(holiday_date: :asc)
  end

  def new
    
  end

  def create
    holiday = Holiday.new holiday_params

    if holiday.save
      flash[:notice] = I18n.t 'new_holiday_success'
    else
      flash[:alert] = I18n.t 'new_holiday_fail'
    end
    redirect_to holidays_path
  end

  def edit
    @holiday = holiday
    @holidays = Holiday.all.order(holiday_date: :asc)
  end

  def update
    if (holiday.update_attributes holiday_params)
      redirect_to edit_holiday_path
      flash[:notice] = I18n.t 'edit_holiday_success'
    else
      redirect_to edit_holiday_path
      flash[:alert] = I18n.t 'edit_holiday_fail'
    end
  end

  def destroy
    if holiday.destroy
      flash[:notice] = I18n.t 'delete_holiday_success'
      redirect_to holidays_path
    else
      flash[:alert] = I18n.t 'delete_holiday_fail'
      redirect_to holidays_path
    end
  end

  protected
    def holiday
      @holiday ||= Holiday.friendly.find(params[:id])
    end

  private
    def holiday_params
      params.require(:holiday).permit(:id, :name, :holiday_date, :holidaytype_id)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/edit.html.erb
<div class="holiday-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Holidays</h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Edit Holiday</strong></h4>
          <%= form_for(@holiday, url: holiday_path(@holiday.slug), html: {method: "put", class: "holiday_form"}) do |f| %>
            <div class="field">
              <label for="holiday_name">Name *</label>
              <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name', required: true %>
            </div>
            <div class="field">
              <label for="holiday_date">Date *</label><br>
              <%= f.date_field :holiday_date, class: 'form-control', required: true, id: 'holiday_picker' %>
            </div>
            
            <div class="field">
              <label for="holiday_type">Type *</label><br>
              <%= f.select :holidaytype_id, Holidaytype.all.collect{|u| [u.full_time_info, u.id]}.sort, {prompt: 'Select'}, {class: 'form-control', required: true, id: 'holiday_type_id'} %>
              <p><%= link_to "Please click here to create new holiday type", holidaytypes_path %></p>
            </div>
            <div class="field display-flex">
              <%= f.submit "Update Holiday", class: "btn btn-primary update-holiday" %>
              <%= link_to "Back", holidays_path %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Existing Holidays</strong></h4>
          <table id="holidayTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Type</th>
                <th colspan="1">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @holidays.each do |holiday| %>
                <tr class="<%= 'active' if params[:id] == holiday.slug %>">
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.holiday_date.strftime("%B %e, %Y") %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.holidaytype.full_time_info %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to 'Delete', holiday_path(holiday.slug), data: { confirm: 'Are you sure?' }, method: :delete %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/holidays/index.html.erb
<div class="holiday-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Holidays</h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Add New Holiday</strong></h4>
          <%= form_for(@holiday, url: holidays_path, html: {class: "holiday_form"}) do |f| %>
            <div class="field">
              <label for="holiday_name">Name *</label>
              <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name', required: true %>
            </div>
            <div class="field">
              <label for="holiday_date">Date *</label><br>
              <%= f.date_field :holiday_date, class: 'form-control', required: true, id: 'holiday_picker', value: Date.today %>
            </div>
            
            <div class="field">
              <label for="holiday_type">Type *</label><br>
              <%= f.select :holidaytype_id, Holidaytype.all.collect{|u| [u.full_time_info, u.id]}.sort, {prompt: 'Select'}, {class: 'form-control', required: true, id: 'holiday_type_id'} %>
              <p><%= link_to "Please click here to create new holiday type", holidaytypes_path %></p>
            </div>
            <%= f.submit "Add New Holiday", class: "btn btn-primary add-holiday" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Existing Holidays</strong></h4>
          <table id="holidayTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Type</th>
                <th colspan="1">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @holidays.each do |holiday| %>
                <tr>
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.holiday_date.strftime("%B %e, %Y") %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_holiday_path(holiday.slug), class: "holiday-link" do %>
                      <%= holiday.holidaytype.full_time_info %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to 'Delete', holiday_path(holiday.slug), data: { confirm: 'Are you sure?' }, method: :delete %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>