config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               user_index GET    /user/index(.:format)          user#index
#              admin_index GET    /admin/index(.:format)         admin#index
#           calendar_index GET    /calendar/index(.:format)      calendar#index
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session GET    /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  users/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) users/passwords#edit
#            user_password PATCH  /users/password(.:format)      users/passwords#update
#                          PUT    /users/password(.:format)      users/passwords#update
#                          POST   /users/password(.:format)      users/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                    users GET    /users(.:format)               users#index
#                          POST   /users(.:format)               users#create
#                 new_user GET    /users/new(.:format)           users#new
#                edit_user GET    /users/:id/edit(.:format)      users#edit
#                     user GET    /users/:id(.:format)           users#show
#                          PATCH  /users/:id(.:format)           users#update
#                          PUT    /users/:id(.:format)           users#update
#                          DELETE /users/:id(.:format)           users#destroy
#                     root GET    /                              users#index
#                 calendar GET    /calendar(.:format)            admin#index

Rails.application.routes.draw do
  get 'user/index'

  get 'admin/index'

  get 'calendar/index'

  devise_scope :user do
    get "/users/edit", to: "users/registrations#edit", as: "edit_user_registration"
    put "/users", to: "users/registrations#update", as: "user_registration"
    # get "/users/cancel", to: "users/registrations#cancel", as: "cancel_user_registration"
    get "/sign_in" => "users/sessions#new"
    get '/users/sign_out' => 'users/sessions#destroy'
    delete "/users", to: "users/registrations#destroy"

    get "check_username", to: "users/sessions#check_username"
    get "check_email", to: "users/sessions#check_email"
    get "check_email_registration", to: "users/sessions#check_email_registration"
    post "/users/new" => "users#new", as: "new_users"
    post "/change_role" => "users#change_role", as: "user_change_role"
    post "/suspend/:id" => "users#suspend", as: "user_suspend"
    post "/reactivate/:id" => "users#reactivate", as: "user_reactivate"
    post "/check_user_email" => "users#check_user_email", as: "check_user_email"
    post "/check_user_name" => "users#check_user_name", as: "check_user_name"
    get "/inactive_status" => "users#inactive_status", as: "inactive_status"
  end
  # devise_for :users, skip: :registration
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }, skip: :registration
  resources :users

  root :to => 'events#summary'

  get "/calendar" => "events#calendar"

  post "/create_event" => "events#create", as: "create_events"
  get "/get_event" => "events#get", as: "get_events"
  post "/update_event" => "events#update", as: "update_events"
  get "/events" => "events#index", as: "events"
  post "/events" => "events#index", as: "events_sort"
  post "/change" => "events#change", as: "change_events"
  get "/events/:event_id" => "events#edit", as: "edit_events"
  delete "/delete_event" => "events#destroy", as: "delete_events"
  # get "/myevents" => "events#my_events", as: "my_events"
  post "/comment" => "events#comment", as: "comment_events"
  get "/events/user_events/:user_id" => "events#user_events", as: "user_events"
  post "/events/user_events/:user_id" => "events#user_events", as: "user_events_sort"

  get "/report" => "events#report", as: "report"
  get "/report_filter" => "events#report_filter", as: "report_filter"
  post "/summary_filter" => "events#summary_filter", as: "summary_filter"
  resources :categories
  
  resources :shifts
  get "/shifts/view" => "shifts#show", as: "view_shift"
  
  resources :lunchtimes
  get "/lunchtimes/view" => "lunchtimes#show", as: "view_lunchtime"

  resources :points do
    get :history, on: :collection
  end
  
  
  resources :penalties

  get "/penalties_summary" => "penalties#summary", as: "penalties_summary"
  get "/penalties/user/:user_id" => "penalties#user", as: "penalties_user"
  get "/penalties/your-penalties" => "penalties#show", as: "show"

  resources :consequences

  post "/penalties/confirmed" => "penalties#confirm_penalty", as: "confirm_penalty"
  get "/help" => "helps#index", as: "help"
  resources :holidays
  resources :holidaytypes
  resources :roles
  resources :departments do
    get :show_users, on: :collection
  end
  post "/call_sub" => "departments#call_sub", as: "call_sub"
end

app/views/layouts/shared/_footer.html.erb
<div class="pull-left">
  <a href="/help" target="_blank">Help</a>
</div>
<div class="pull-right">
  <a href="https://cvlinens.com">CV Linens</a>
</div>
<div class="clearfix"></div>

app/views/layouts/shared/_help_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <%= link_to root_path, class: 'site_title', title: 'CVLinens' do %>
    <img src="<%= image_url('logo2.png', :alt => 'CVLinens') %>">
  <% end %>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2>User</h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />

<!-- sidebar menu -->
<div id="sidebar-menu" class="help_menu_side hidden-print help_menu">
  <div class="menu_section">
    <h3>General</h3>
    <ul class="nav side-menu">
      <li><a href="/">Go to Dashboard</a></li>
      <li><a href="#about-event">About Creating Event</a></li>
      <li><a href="#about-category">About Category</a></li>
    </ul>
  </div>
  <div class="menu_section">
    <h3>Point System</h3>
    <ul class="nav side-menu">
      <li><a href="#about-shift">About Shift</a></li>
      <li><a href="#about-lunchtime">About Lunchtime</a></li>
      <li><a href="#about-point">About Point</a></li>
      <li><a href="#about-consequence">About Consequence</a></li>
    </ul>
  </div>
  
</div>

<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<%# <div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div> %>
<!-- /menu footer buttons -->

app/views/layouts/shared/_leftnav.html.erb
<div class="navbar nav_title" style="border: 0;">
  <%= link_to root_path, class: 'site_title', title: 'CVLinens' do %>
    <img src="<%= image_url('logo2.png', :alt => 'CVLinens') %>">
  <% end %>
</div>

<div class="clearfix"></div>

<!-- menu profile quick info -->
<div class="profile clearfix">
  <div class="profile_pic">
    <% if current_user.admin? %>
      <img src="<%= image_url('img.jpg', :alt => 'User') %>" class="img-circle profile_img">
    <% else %>
      <img src="<%= image_url('img2.jpg', :alt => 'User') %>" class="img-circle profile_img">
    <% end %>
  </div>
  <div class="profile_info">
    <span>Welcome,</span>
    <h2><%= current_user.full_name %></h2>
  </div>
</div>
<!-- /menu profile quick info -->

<br />
<% if current_user.active? %>
  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><%= link_to "Summary", root_path, class: [("active" if params[:controller] == 'events' && params[:action] == 'summary')] %></li>
        <li><%= link_to "Calendar", calendar_path, class: [("active" if params[:controller] == 'events' && params[:action] == 'calendar')] %></li>
        <li><%= link_to "Events", events_path, class: [("active" if params[:controller] == 'events' && params[:action] != 'calendar' && params[:action] != 'summary' && params[:action] != 'report')]  %></li>
        
      </ul>
    </div>
    <% if current_user.admin? || current_user.user_perm? || current_user.user_role_perm? || current_user.department_perm? || current_user.category_perm? || current_user.holiday_perm? %>
      <div class="menu_section">
        <h3>Special</h3>
        <ul class="nav side-menu">
          <% if current_user.user_perm? %>
            <li><%= link_to "User Management", users_path, class: [("active" if params[:controller] == 'users')] %></li>
          <% end %>
          <% if current_user.user_role_perm? %>
            <li><%= link_to "User Role Management", roles_path, class: [("active" if params[:controller] == 'roles')] %></li>
          <% end %>
          <% if current_user.department_perm? %>
            <li><%= link_to "Department", departments_path, class: [("active" if params[:controller] == 'departments')] %></li>
          <% end %>
          <% if current_user.admin? %>
            <li><%= link_to "Report", report_path, class: [("active" if params[:controller] == 'events' && params[:action] == 'report')] %></li>
          <% end %>
          <% if current_user.category_perm? %>
            <li><%= link_to "Category", categories_path, class: [("active" if params[:controller] == 'categories')] %></li>
          <% end %>
          <% if current_user.holiday_perm? %>
            <li><%= link_to "Holiday", holidays_path, class: [("active" if params[:controller] == 'holidays')] %></li>
          <% end %>
        </ul>
      </div>
    <% elsif current_user.manager? && !current_user.department_perm? %>
      <div class="menu_section">
        <h3>Special</h3>
        <ul class="nav side-menu">
          <li><%= link_to "Department", show_users_departments_path, class: [("active" if params[:controller] == 'departments')] %></li>
        </ul>
      </div>
    <% end %>
    <% if current_user.admin? || current_user.shift_perm? || current_user.lunchtime_perm? || current_user.point_perm? || current_user.penalty_perm? || current_user.consequence_perm? %>
      <div class="menu_section">
        <h3>Point System</h3>
        <ul class="nav side-menu">
          <% if current_user.shift_perm? %>
            <li><%= link_to "Shifts", shifts_path, class: [("active" if params[:controller] == 'shifts')] %></li>
          <% end %>
          <% if current_user.lunchtime_perm? %>
            <li><%= link_to "Lunchtimes", lunchtimes_path, class: [("active" if params[:controller] == 'lunchtimes')] %></li>
          <% end %>
          <% if current_user.point_perm? %>
            <li><%= link_to "Point Management", points_path, class: [("active" if params[:controller] == 'points')] %></li>
          <% end %>
          <% if current_user.penalty_perm? %>
            <li><%= link_to "Penalty Management", penalties_path, class: [("active" if params[:controller] == 'penalties' && params[:action] != 'summary' && params[:action] != 'user')] %></li>
            <li><%= link_to "User Penalties", penalties_summary_path, class: [("active" if params[:controller] == 'penalties' && (params[:action] == 'summary' || params[:action] == 'user'))] %></li>
          <% end %>
          <% if current_user.consequence_perm? %>
            <li><%= link_to "Consequences", consequences_path, class: [("active" if params[:controller] == 'consequences')] %></li>
          <% end %>
        </>
      </div>
    <% else %>
      <div class="menu_section">
        <h3>Point System</h3>
        <ul class="nav side-menu">
          <li><%= link_to "View Shifts", view_shift_path %></li>
          <li><%= link_to "View Lunchtimes", view_lunchtime_path %></li>
          <li><%= link_to "View Penalties", show_path %></li>
        </ul>
      </div>
    <% end %>
  </div>
<% end %>
<!-- /sidebar menu -->

<!-- /menu footer buttons -->
<%# <div class="sidebar-footer hidden-small">
  <a data-toggle="tooltip" data-placement="top" title="Settings">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="FullScreen">
    <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Lock">
    <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
  </a>
  <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
  </a>
</div> %>
<!-- /menu footer buttons -->

app/views/layouts/shared/_topnav.html.erb
<div class="nav toggle">
  <%# <a id="menu_toggle"><i class="fa fa-bars"></i></a> %>
</div>

<ul class="nav navbar-nav navbar-right">
  <li class="">
    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <% if current_user.admin? %>
        <img src="<%= image_url('img.jpg', :alt => 'User') %>">
      <% else %>
        <img src="<%= image_url('img2.jpg', :alt => 'User') %>">
      <% end %>
      <span><%= current_user.first_name %> <%= current_user.last_name %></span>
      <span class=" fa fa-angle-down"></span>
    </a>
    <ul class="dropdown-menu dropdown-usermenu pull-right">
      <li>
        <%= link_to edit_user_registration_path do %>
          <span>Profiles</span>
        <% end %>
      </li>
      <li><%= link_to 'Help', help_path %></li>
      <li><a href="/users/sign_out"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
    </ul>
  </li>

</ul>