config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               user_index GET    /user/index(.:format)          user#index
#              admin_index GET    /admin/index(.:format)         admin#index
#           calendar_index GET    /calendar/index(.:format)      calendar#index
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session GET    /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  users/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) users/passwords#edit
#            user_password PATCH  /users/password(.:format)      users/passwords#update
#                          PUT    /users/password(.:format)      users/passwords#update
#                          POST   /users/password(.:format)      users/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                    users GET    /users(.:format)               users#index
#                          POST   /users(.:format)               users#create
#                 new_user GET    /users/new(.:format)           users#new
#                edit_user GET    /users/:id/edit(.:format)      users#edit
#                     user GET    /users/:id(.:format)           users#show
#                          PATCH  /users/:id(.:format)           users#update
#                          PUT    /users/:id(.:format)           users#update
#                          DELETE /users/:id(.:format)           users#destroy
#                     root GET    /                              users#index
#                 calendar GET    /calendar(.:format)            admin#index

Rails.application.routes.draw do
  get 'user/index'

  get 'admin/index'

  get 'calendar/index'

  devise_scope :user do
    get "/users/edit", to: "users/registrations#edit", as: "edit_user_registration"
    put "/users", to: "users/registrations#update", as: "user_registration"
    # get "/users/cancel", to: "users/registrations#cancel", as: "cancel_user_registration"
    get "/sign_in" => "users/sessions#new"
    get '/users/sign_out' => 'users/sessions#destroy'
    delete "/users", to: "users/registrations#destroy"

    get "check_username", to: "users/sessions#check_username"
    get "check_email", to: "users/sessions#check_email"
    get "check_email_registration", to: "users/sessions#check_email_registration"
    post "/users/new" => "users#new", as: "new_users"
    post "/change_role" => "users#change_role", as: "user_change_role"
    post "/suspend/:id" => "users#suspend", as: "user_suspend"
    post "/reactivate/:id" => "users#reactivate", as: "user_reactivate"
    post "/check_user_email" => "users#check_user_email", as: "check_user_email"
    post "/check_user_name" => "users#check_user_name", as: "check_user_name"
    get "/inactive_status" => "users#inactive_status", as: "inactive_status"
  end
  # devise_for :users, skip: :registration
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }, skip: :registration
  resources :users

  root :to => 'events#summary'

  get "/calendar" => "events#calendar"

  post "/create_event" => "events#create", as: "create_events"
  get "/get_event" => "events#get", as: "get_events"
  post "/update_event" => "events#update", as: "update_events"
  get "/events" => "events#index", as: "events"
  post "/events" => "events#index", as: "events_sort"
  post "/change" => "events#change", as: "change_events"
  get "/events/:event_id" => "events#edit", as: "edit_events"
  delete "/delete_event" => "events#destroy", as: "delete_events"
  # get "/myevents" => "events#my_events", as: "my_events"
  post "/comment" => "events#comment", as: "comment_events"
  get "/events/user_events/:user_id" => "events#user_events", as: "user_events"
  post "/events/user_events/:user_id" => "events#user_events", as: "user_events_sort"

  get "/report" => "events#report", as: "report"
  get "/report_filter" => "events#report_filter", as: "report_filter"
  post "/summary_filter" => "events#summary_filter", as: "summary_filter"
  resources :categories
  
  resources :shifts
  get "/shifts/view" => "shifts#show", as: "view_shift"
  
  resources :lunchtimes
  get "/lunchtimes/view" => "lunchtimes#show", as: "view_lunchtime"

  resources :points do
    get :history, on: :collection
  end
  
  
  resources :penalties

  get "/penalties_summary" => "penalties#summary", as: "penalties_summary"
  get "/penalties/user/:user_id" => "penalties#user", as: "penalties_user"
  get "/penalties/your-penalties" => "penalties#show", as: "show"

  resources :consequences

  post "/penalties/confirmed" => "penalties#confirm_penalty", as: "confirm_penalty"
  get "/help" => "helps#index", as: "help"
  resources :holidays
  resources :holidaytypes
  resources :roles
  resources :departments do
    get :show_users, on: :collection
  end
  post "/call_sub" => "departments#call_sub", as: "call_sub"
end

app/models/penalty.rb
# == Schema Information
#
# Table name: penalties
#
#  id          :bigint           not null, primary key
#  apply_date  :datetime
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  point_id    :integer
#  user_id     :bigint
#

class Penalty < ApplicationRecord
  belongs_to :user
  belongs_to :point, optional: true

  after_destroy :update_consequence_id


  def update_consequence_id
    if self.user.find_consequence_id != self.user.consequence_id
      self.user.confirm_penalty(self.user.find_consequence_id)
    end
  end


  
end

app/controllers/penalties_controller.rb
class PenaltiesController < ApplicationController
  before_action :authenticate_user!, except: []
  layout "index"
  before_action :check_active_status
  before_action :check_permission, except: [:show, :render_404]
   
  def check_permission
    redirect_to root_path unless current_user.admin? || current_user.penalty_perm?
  end

  def check_active_status
    redirect_to inactive_status_path if current_user.inactive?
  end

  def index
    @points = Point.all
    @enabled_points = Point.all.where(disabled: false).order(name: :asc)
    @penalties = Penalty.all.order(apply_date: :desc)
    @penalty = Penalty.new
  end

  def new
    @penalty = Penalty.new
  end

  def create
    user_id = params[:penalty][:user_id]
    point_id = params[:penalty][:point_id]
    description = params[:penalty][:description]
    apply_date = params[:penalty][:apply_date]
    h = Time.now.hour
    m = Time.now.min
    s = Time.now.sec
    apply_date = DateTime.parse(apply_date).change(hour: h, min: m, sec: s)
    apply_date_tz = apply_date.asctime.in_time_zone(current_user.time_zone)
    apply_date_UTC = apply_date_tz.utc

    user = User.find(user_id)
    penalty = Penalty.new user_id: user_id, point_id: point_id, description: description, apply_date: apply_date_UTC

    if penalty.save
      # user.apply_penalty(point_id)
      if user.check_penalty?
        redirect_to penalties_summary_path
        flash[:alert] = I18n.t 'reach_penalty_success'
      else
        flash[:notice] = I18n.t 'new_penalty_success'
        redirect_to penalties_path
      end
    else
      flash[:alert] = I18n.t 'new_penalty_fail'
      redirect_to penalties_path
    end
  end

  def edit
    @points = Point.all
    @enabled_points = Point.all.where(disabled: false).order(name: :asc)
    @penalties = Penalty.all.order(apply_date: :desc)
    @penalty = penalty
  end

  def update
    user_id = params[:penalty][:user_id]
    point_id = params[:penalty][:point_id]
    description = params[:penalty][:description]
    apply_date = params[:penalty][:apply_date]
    h = Time.now.hour
    m = Time.now.min
    s = Time.now.sec
    apply_date = DateTime.parse(apply_date).change(hour: h, min: m, sec: s)
    apply_date_tz = apply_date.asctime.in_time_zone(current_user.time_zone)
    apply_date_UTC = apply_date_tz.utc

    if penalty.update_attributes user_id: user_id, point_id: point_id, description: description, apply_date: apply_date_UTC
      flash[:notice] = I18n.t 'edit_penalty_success'
    else
      flash[:alert] = I18n.t 'edit_penalty_fail'
    end
    redirect_to edit_penalty_path
  end

  def summary
    @users = User.all.order(:first_name)
    @penalties = Penalty.all

    filtered_datas = []
    consequences = Consequence.all
    consequences.each do |consequence|
      consequence_point = consequence.reach_point
      if consequence == Consequence.last
        break
      else
        consequence_next_point = consequence.next.reach_point
      end
      filtered = []
      User.all.each do |u|
        if u.total_penalty >= consequence_point && u.total_penalty < consequence_next_point
          if u.consequence_id != consequence.id
            filtered << u
            filtered << consequence
            filtered_datas << filtered
          end
        end
      end
    end
    @filtered_datas = filtered_datas
    
  end

  def confirm_penalty
    id = params[:id]
    consequence_id = params[:consequence_id]
    user = User.find(id)
    user.confirm_penalty(consequence_id)
    data = {
      user_id: user.id,
      flag_color: user.consequence.flag_color,
      consequence_full_info: user.consequence.full_info
    }
    render json: data
    
  end

  def user
    user_id = params[:user_id]
    @user = User.find_by(slug: user_id)
    @penalties = @user.penalties
    
  end

  def show
    user_id = params[:user_id]
    @user = User.find_by(slug: user_id)
  end

  def destroy
    user_id = penalty.user_id
    user = User.find(user_id)

    if penalty.destroy
      # if user.consequence_id != 0
      #   user.update_consequence_id
      # end
      flash[:notice] = I18n.t 'delete_penalty_success'
    else
      flash[:alert] = I18n.t 'delete_penalty_fail'
      render_404
    end
    redirect_to penalties_path
    
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  protected
    def penalty
      @penalty ||= Penalty.find(params[:id])
    end

  # private
  #   def penalty_params
  #     params.require(:penalty).permit(:id, :user_id, :point_id, :description, :apply_date)
  #   end
end

app/helpers/penalties_helper.rb
module PenaltiesHelper
end

app/views/penalties/edit.html.erb
<div class="penalty-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Penalties</h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12">
      <div class="x_panel">
        <div class="x_content" id="edit_penalty_form">
          <h4><strong>Update Penalty</strong></h4>
          <%= form_for(@penalty, url: penalty_path(@penalty.id), html: {method: "put", class: "penalty_form"}) do |f| %>
            <div class="field">
              <label for="user_id">User *</label>
              <%= f.select :user_id , User.all.collect {|u| [u.full_name, u.id]}.group_by{ |u| u.first[0,1].upcase }.sort, {prompt: 'Select'}, {class: "form-control", required: true} %>
            </div>
            <div class="field">
              <label for="penalty_point">Point *</label>
              <%= f.select :point_id, @enabled_points.collect {|u| [u.name, u.id]}.sort, {prompt: 'Select'}, {class: "form-control", required: true} %>
            </div>
            <div class="field">
              <label for="description">Description *</label>
              <%= f.text_area :description, class: "form-control", row: 4, required: true %>
            </div>
            <div class="field">
              <label for="apply_date">Apply date *</label>
              <%= f.date_field :apply_date, class: 'form-control' %>
            </div>
            <div class="field display-flex">
              <%= submit_tag "Update Penalty", class: "btn btn-primary update-penalty" %>
              <%= link_to "Back", penalties_path %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-sm-7 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Penalty Rule</strong></h4>
          <table id="pointTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Point</th>
              </tr>
            </thead>

            <tbody>
              <% @enabled_points.each do |point| %>
                <tr>
                  <td><%= point.name %></td>
                  <td><%= point.description %></td>
                  <td><%= point.penalty_point %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Penalty History</strong></h4>
          <table id="penaltyDetailTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>User Name</th>
                <th>Penalty Rule</th>
                <th>Point</th>
                <th>Description</th>
                <th>Applied Date</th>
                <th colspan="2" class="text-center">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @penalties.each do |penalty| %>
                <tr class="<%= 'active' if params[:id] == penalty.id.to_s %>">
                  <td>
                    <p><%= penalty.user.full_name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.penalty_point %></p>
                  </td>
                  <td>
                    <p><%= penalty.description %></p>
                  </td>
                  <td>
                    <p><%= Dates.convertedTime(penalty.apply_date, current_user.time_zone) %></p>
                  </td>
                  <td class="text-center action">
                    <%= link_to "Edit", edit_penalty_path(penalty.id) %>
                  </td>
                  <td class="text-center action">
                    <%= link_to "Delete", penalty_path(penalty.id), data: { confirm: 'Are you sure?' }, method: "delete" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/penalties/index.html.erb
<div class="penalty-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Penalties</h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-4 col-sm-4 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>New Penalty</strong></h4>
          <%= form_for(@penalty, url: penalties_path, html: {class: "penalty_form"}) do |f| %>
            <div class="field">
              <label for="user_id">User *</label>
              <%= f.select :user_id, User.all.collect {|u| [u.full_name, u.id]}.group_by{ |u| u.first[0,1].upcase }.sort, {prompt: 'Select'}, {class: "form-control", required: true} %>
            </div>
            <div class="field">
              <label for="penalty_point">Point *</label>
              <%= f.select :point_id, @enabled_points.collect {|u| [u.name, u.id]}.sort, {prompt: 'Select'}, {class: "form-control", required: true} %>
            </div>
            <div class="field">
              <label for="description">Description *</label>
              <%= f.text_area :description, class: 'form-control', rows: 4, required: true %>
            </div>
            <div class="field">
              <label for="apply_date">Apply date *</label>
              <%= f.date_field :apply_date, class: 'form-control', value: Date.today %>
            </div>
           
            <%= submit_tag "Apply Penalty To User", class: "btn btn-primary add-point" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-sm-7 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Penalty Rule</strong></h4>
          <table id="pointTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Point</th>
              </tr>
            </thead>

            <tbody>
              <% @enabled_points.each do |point| %>
                <tr>
                  <td><%= point.name %></td>
                  <td><%= point.description %></td>
                  <td><%= point.penalty_point %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Penalty History</strong></h4>
          <table id="penaltyTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>User Name</th>
                <th>Penalty Rule</th>
                <th>Point</th>
                <th>Description</th>
                <th>Applied Date</th>
                <th colspan="2" class="text-center">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @penalties.each do |penalty| %>
                <tr>
                  <td>
                    <p><%= penalty.user.full_name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.penalty_point %></p>
                  </td>
                  <td>
                    <p><%= penalty.description %></p>
                  </td>
                  <% created_date = Dates.convertedTime(penalty.apply_date, current_user.time_zone) %>
                  <% parse_date = DateTime.parse(created_date) %>
                  <td data-sort="<%= parse_date.strftime("%Y%m%d%H%M%s") %>">
                    <span><%= created_date %></span>
                  </td>
                  <td class="text-center action">
                    <%= link_to "Edit", edit_penalty_path(penalty.id) %>
                  </td>
                  <td class="text-center action">
                    <%= link_to "Delete", penalty_path(penalty.id), data: { confirm: 'Are you sure?' }, method: "delete" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/penalties/show.html.erb
<div class="users-penalty-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Your Penalties</h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <div class="clearfix"></div>
          <div class="user-penalty display-flex">
            <div><strong>Total Penalty Point</strong>: <%= current_user.total_penalty %></div>
            <div class="flex-1"><strong>Point Limit</strong>: <%= current_user.user_point_limit %></div>
            <% if current_user.consequence_id != 0 %>
              <div class="flag-color-svg">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" style="fill: <%= current_user.consequence.flag_color %>" viewBox="0 0 24 24"><path style="stroke: #000000; stroke-width: 0.3;" d="M4 24h-2v-24h2v24zm18-22h-16v12h16l-4-5.969 4-6.031z"/></svg>
              </div>
            <% end %>
          </div>
          <% if current_user.consequence_id != 0 %>
            <div class="penalty-warning" style="background: <%= current_user.consequence.flag_color %>">
              <div>Warning: You reached to <%= current_user.consequence.full_info %></div>
            </div>
          <% end %>
        </div>
        <div class="x_content">
          <table id="userPenaltyTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Point</th>
                <th>Description</th>
                <th>Applied Date</th>
              </tr>
            </thead>

            <tbody>
              <% current_user.penalties.each do |penalty| %>
                <tr>
                  <td>
                    <p><%= penalty.point.name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.penalty_point %></p>
                  </td>
                  <td>
                    <p><%= penalty.description %></p>
                  </td>
                  <td>
                    <p><%= Dates.convertedTime(penalty.apply_date, current_user.time_zone) %></p>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/penalties/summary.html.erb
<div class="penalty-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Users</h3>
    </div>
  </div>

  <div class="clearfix"></div>
  <% if @filtered_datas.present? %>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <h4><strong>Notifications</strong></h4>
            <table id="penaltyNotificationTable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>User Name</th>
                  <th>Reached Penalty Point</th>
                  <th>User Point Limit(yearly)</th>
                  <th>Total Penalty counts</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>

              <tbody>
                <% @filtered_datas.each do |user, consequence| %>
                  <tr>
                    <td>
                      <p><%= user.full_name %></p>
                    </td>
                    <td>
                      <p><%= user.total_penalty %></p>
                    </td>
                    <td>
                      <p><%= user.user_point_limit %></p>
                    </td>
                    <td>
                      <p><%= user.penalties.count %></p>
                    </td>
                    <td>
                      <div class="flag-consequence display-flex">
                        <div class="flag-color-svg">
                          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" style="fill: <%= consequence.flag_color %>" viewBox="0 0 24 24"><path style="stroke: #000000; stroke-width: 0.3;" d="M4 24h-2v-24h2v24zm18-22h-16v12h16l-4-5.969 4-6.031z"/></svg>
                        </div>
                        <p><%= consequence.try(:full_info) %></p>
                      </div>
                    </td>
                    <td>
                      <button type="button" class="btn btn-warning btn-confirm-penalty" data-user-id="<%= user.id %>" data-consequence-id="<%= consequence.id %>">Confirm</button>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>User Penalty Summary</strong></h4>
          <table id="penaltySummaryTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>User Name</th>
                <th>Total Penalty</th>
                <th>User Point Limit(yearly)</th>
                <th>Total Penalty counts</th>
                <th>Consequence</th>
                <th>Created at</th>
                <th>Detail view</th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <p><%= user.full_name %></p>
                  </td>
                  <td>
                    <p><%= user.total_penalty %></p>
                  </td>
                  <td>
                    <p><%= user.user_point_limit %></p>
                  </td>
                  <td>
                    <p><%= user.penalties.count %></p>
                  </td>
                  <td class="consequence-step" data-id="<%= user.id %>">
                    <% if user.consequence.present? %>
                    <div class="flag-consequence display-flex">
                      <div class="flag-color-svg">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" style="fill: <%= user.consequence.flag_color %>" viewBox="0 0 24 24"><path style="stroke: #000000; stroke-width: 0.3;" d="M4 24h-2v-24h2v24zm18-22h-16v12h16l-4-5.969 4-6.031z"/></svg>
                      </div>
                      <p><%= user.consequence.try(:full_info) %></p>
                    </div>
                    <% end %>
                  </td>
                  <td>
                    <p><%= Dates.convertedTime(user.created_at, current_user.time_zone) %></p>
                  </td>
                  <td>
                    <%= link_to "Detail view", penalties_user_path(user.slug), class: "btn btn-basic" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/penalties/user.html.erb
<div class="users-penalty-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>User Penalties</h3>
    </div>
  </div>
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2><%= @user.full_name %> <small><%= @user.user_role %></small></h2>
          <div class="clearfix"></div>
          <div class="user-penalty display-flex">
            <div><strong>Total Penalty Point</strong>: <%= @user.total_penalty %></div>
            <div class="flex-1"><strong>Point Limit</strong>: <%= @user.user_point_limit %></div>
            <% if @user.consequence_id != 0 %>
              <div class="flag-color-svg">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" style="fill: <%= @user.consequence.flag_color %>" viewBox="0 0 24 24"><path style="stroke: #000000; stroke-width: 0.3;" d="M4 24h-2v-24h2v24zm18-22h-16v12h16l-4-5.969 4-6.031z"/></svg>
              </div>
            <% end %>
          </div>
          <% if @user.consequence_id != 0 %>
            <div class="penalty-warning" style="background: <%= @user.consequence.flag_color %>">
              <div>Warning: This user reached to <%= @user.consequence.full_info %></div>
            </div>
          <% end %>
        </div>
        <div class="x_content">
          <table id="userPenaltyTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Point</th>
                <th>Description</th>
                <th>Applied Date</th>
              </tr>
            </thead>

            <tbody>
              <% @penalties.each do |penalty| %>
                <tr>
                  <td>
                    <p><%= penalty.point.name %></p>
                  </td>
                  <td>
                    <p><%= penalty.point.penalty_point %></p>
                  </td>
                  <td>
                    <p><%= penalty.description %></p>
                  </td>
                  <td>
                    <p><%= Dates.convertedTime(penalty.apply_date, current_user.time_zone) %></p>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>