config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                    Controller#Action
#               user_index GET    /user/index(.:format)          user#index
#              admin_index GET    /admin/index(.:format)         admin#index
#           calendar_index GET    /calendar/index(.:format)      calendar#index
#         new_user_session GET    /users/sign_in(.:format)       users/sessions#new
#             user_session POST   /users/sign_in(.:format)       users/sessions#create
#     destroy_user_session GET    /users/sign_out(.:format)      users/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)  users/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) users/passwords#edit
#            user_password PATCH  /users/password(.:format)      users/passwords#update
#                          PUT    /users/password(.:format)      users/passwords#update
#                          POST   /users/password(.:format)      users/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)        users/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)       users/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          users/registrations#edit
#        user_registration PATCH  /users(.:format)               users/registrations#update
#                          PUT    /users(.:format)               users/registrations#update
#                          DELETE /users(.:format)               users/registrations#destroy
#                          POST   /users(.:format)               users/registrations#create
#                    users GET    /users(.:format)               users#index
#                          POST   /users(.:format)               users#create
#                 new_user GET    /users/new(.:format)           users#new
#                edit_user GET    /users/:id/edit(.:format)      users#edit
#                     user GET    /users/:id(.:format)           users#show
#                          PATCH  /users/:id(.:format)           users#update
#                          PUT    /users/:id(.:format)           users#update
#                          DELETE /users/:id(.:format)           users#destroy
#                     root GET    /                              users#index
#                 calendar GET    /calendar(.:format)            admin#index

Rails.application.routes.draw do
  get 'user/index'

  get 'admin/index'

  get 'calendar/index'

  devise_scope :user do
    get "/users/edit", to: "users/registrations#edit", as: "edit_user_registration"
    put "/users", to: "users/registrations#update", as: "user_registration"
    # get "/users/cancel", to: "users/registrations#cancel", as: "cancel_user_registration"
    get "/sign_in" => "users/sessions#new"
    get '/users/sign_out' => 'users/sessions#destroy'
    delete "/users", to: "users/registrations#destroy"

    get "check_username", to: "users/sessions#check_username"
    get "check_email", to: "users/sessions#check_email"
    get "check_email_registration", to: "users/sessions#check_email_registration"
    post "/users/new" => "users#new", as: "new_users"
    post "/change_role" => "users#change_role", as: "user_change_role"
    post "/suspend/:id" => "users#suspend", as: "user_suspend"
    post "/reactivate/:id" => "users#reactivate", as: "user_reactivate"
    post "/check_user_email" => "users#check_user_email", as: "check_user_email"
    post "/check_user_name" => "users#check_user_name", as: "check_user_name"
    get "/inactive_status" => "users#inactive_status", as: "inactive_status"
  end
  # devise_for :users, skip: :registration
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }, skip: :registration
  resources :users

  root :to => 'events#summary'

  get "/calendar" => "events#calendar"

  post "/create_event" => "events#create", as: "create_events"
  get "/get_event" => "events#get", as: "get_events"
  post "/update_event" => "events#update", as: "update_events"
  get "/events" => "events#index", as: "events"
  post "/events" => "events#index", as: "events_sort"
  post "/change" => "events#change", as: "change_events"
  get "/events/:event_id" => "events#edit", as: "edit_events"
  delete "/delete_event" => "events#destroy", as: "delete_events"
  # get "/myevents" => "events#my_events", as: "my_events"
  post "/comment" => "events#comment", as: "comment_events"
  get "/events/user_events/:user_id" => "events#user_events", as: "user_events"
  post "/events/user_events/:user_id" => "events#user_events", as: "user_events_sort"

  get "/report" => "events#report", as: "report"
  get "/report_filter" => "events#report_filter", as: "report_filter"
  post "/summary_filter" => "events#summary_filter", as: "summary_filter"
  resources :categories
  
  resources :shifts
  get "/shifts/view" => "shifts#show", as: "view_shift"
  
  resources :lunchtimes
  get "/lunchtimes/view" => "lunchtimes#show", as: "view_lunchtime"

  resources :points do
    get :history, on: :collection
  end
  
  
  resources :penalties

  get "/penalties_summary" => "penalties#summary", as: "penalties_summary"
  get "/penalties/user/:user_id" => "penalties#user", as: "penalties_user"
  get "/penalties/your-penalties" => "penalties#show", as: "show"

  resources :consequences

  post "/penalties/confirmed" => "penalties#confirm_penalty", as: "confirm_penalty"
  get "/help" => "helps#index", as: "help"
  resources :holidays
  resources :holidaytypes
  resources :roles
  resources :departments do
    get :show_users, on: :collection
  end
  post "/call_sub" => "departments#call_sub", as: "call_sub"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id             :bigint           not null, primary key
#  default_option :boolean          default(FALSE)
#  description    :text
#  name           :string
#  slug           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_categories_on_name  (name) UNIQUE
#  index_categories_on_slug  (slug) UNIQUE
#

class Category < ApplicationRecord
  has_many :event
  validates_uniqueness_of :name
  extend FriendlyId
  friendly_id :name, use: :slugged

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: []
  layout "index"
  
  before_action :check_active_status
  before_action :check_permission, except: [:render_404]
   
  def check_permission
    redirect_to root_path unless current_user.admin? || current_user.category_perm?
  end

  def check_active_status
    redirect_to inactive_status_path if current_user.inactive?
  end

  def index
    @categories_default = Category.all.where(default_option: true).order(name: :asc)
    @categories_non_default = Category.all.where(default_option: false).order(name: :asc)

    @categories = @categories_default + @categories_non_default
  end

  def new
    name = params[:category_name]
    description = params[:category_description]
    default_option = params[:default_option]

    if default_option.present?
      default_option = true
    else
      default_option = false
    end

    category = Category.new(name: name, description: description, default_option: default_option)

    if category.save
      flash[:notice] = I18n.t 'new_category_success'
      redirect_to categories_path
    else
      redirect_to categories_path
      flash[:alert] = I18n.t 'new_category_fail'
    end
  end

  def edit
    @categories_default = Category.all.where(default_option: true).order(name: :asc)
    @categories_non_default = Category.all.where(default_option: false).order(name: :asc)

    @categories = @categories_default + @categories_non_default

    @category = category
    @events = current_user.events_by_role.where(category_id: category.id)
  end

  def update
    name = params[:category_name]
    description = params[:category_description]
    default_option = params[:default_option]

    if default_option.present?
      default_option = true
    else
      default_option = false
    end

    if current_user.admin?
      if (category.update_attributes(name: name, description: description, default_option: default_option))
        redirect_to edit_category_path
        flash[:notice] = I18n.t 'edit_category_success'
      else
        redirect_to edit_category_path
        flash[:alert] = I18n.t 'edit_category_fail'
      end
    end
  end

  def destroy
    category_id = category.id
    if current_user.admin?
      if category.default_option? and Category.where(default_option: true).count == 1
        flash[:alert] = I18n.t 'no_permission_last_default_category'
      else
        if category.event.blank?
          if category.destroy
            events = Event.where(category_id: category_id)
            events.each do |event|
              if event.update_attribute('category_id', 0)
                puts "OKay"
              else
                puts "no"
              end
            end
            flash[:notice] = I18n.t 'delete_category_success'
          else
            flash[:alert] = I18n.t 'delete_category_fail'
          end
        else
          flash[:alert] = I18n.t 'delete_category_no_empty'
        end
      end
    else
      flash[:alert] = I18n.t 'no_permission_category_creation'
    end

    redirect_to categories_path
  end

  def render_404
    respond_to do |format|
      format.html { render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found }
      format.xml  { head :not_found }
      format.any  { head :not_found }
    end
  end

  protected
    def category
      @category ||= Category.friendly.find(params[:id]) 
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="category-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Category - <%= @category.name %></h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-4 col-sm-5 col-xs-12">
      <div class="x_panel">
        <div class="x_content" id="edit_category_form">
          <h4><strong>Edit Category</strong></h4>
          <%= form_tag category_path(@category.slug), {method: "put", class: "category_form"} do %>
            <div class="field">
              <label for="category_name">Name *</label>
              <input type="text" name="category_name" class="form-control" id="category_name" value="<%= @category.name %>" placeholder="" required="required" />
            </div>
            <div class="field">
              <label for="category_description">Description</label>
              <textarea class="form-control" rows="4" id="category_description" name="category_description"><%= @category.description %></textarea>
            </div>
            <div class="field display-flex">
              <% if @category.default_option.present? %>
                <input type="checkbox" name="default_option" id="default_option" checked />
              <% else %>
                <input type="checkbox" name="default_option" id="default_option" />
              <% end %>
              <label for="default_option" class="default_label">Selectable for everyone?</label>
            </div>
            <div class="field display-flex">
              <%= submit_tag "Update Category", class: "btn btn-primary update-category" %>
              <%= link_to "Back", categories_path %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-sm-7 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Existing Categories</strong></h4>
          <table id="categoryTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Selectable for everyone?</th>
                <th>Count</th>
                <th colspan="1">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @categories.each do |category| %>
                <tr class="<%= 'active' if params[:id] == category.slug %>">
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <%= category.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <%= category.description %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <% if category.default_option? %>
                        <img src="<%= image_url('valid.png', alt: 'Yes') %>" class="category_icon" >
                      <% else %>
                        <img src="<%= image_url('invalid.png', alt: 'Yes') %>" class="category_icon" >
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= Event.all.where(category_id: category.id).count %></td>
                  <td>
                    <%= link_to 'Delete', category_path(category.slug), data: { confirm: 'Are you sure?' }, method: :delete %>
                  </td>
                </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <div class="heading">
            <h2>Events</h2>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <table id="categoryEventTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th class="__category_">Category</th>
                <th class="__description_">Description</th>
                <th class="__username_">User Name</th>
                <th class="__startdate_">Start Date</th>
                <th class="__enddate_">End Date</th>
                <th class="__submitdate_">Submitted Date</th>
                <th class="__status_">Status</th>
              </tr>
            </thead>
            <tbody>
            <%# timeZone = cookies[:time_zone] %>
              <% @events.each do |event| %>
                <tr>
                  <td>
                    <%= link_to edit_events_path(event.id), class: "event_link" do %>
                      <% if event.category_id == 0 %>
                        <span>-- No category --</span>
                      <% else %>
                        <span><%= event.category_name %></span>
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_events_path(event.id), class: "event_link" do %>
                      <span><%= event.description %></span>
                      <% if event.comment.present? %>
                        <img src="<%= image_url('comment.png', :alt => 'comment') %>" class="icon_comment">
                      <% end %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to user_events_path(event.user.slug), class: "event_link" do %>
                      <span><%= event.user.full_name %></span>
                    <% end %>
                  </td>
                  <% str_start = Time.use_zone(@time_zone) {event.start_D} %>
                  <% parse_start = DateTime.parse(str_start) %>

                  <td data-sort="<%= parse_start.strftime("%Y%m%d%H%M%s") %>">
                    <%= link_to edit_events_path(event.id), class: "event_link" do %>
                      <time><%= str_start %></time>
                    <% end %>
                  </td>

                  <% str_end = Time.use_zone(@time_zone) {event.end_D} %>
                  <% parse_end = DateTime.parse(str_end) %>
                  <td data-sort="<%= parse_end.strftime("%Y%m%d%H%M%s") %>">
                    <%= link_to edit_events_path(event.id), class: "event_link" do %>
                      <time><%= str_end %></time>
                    <% end %>
                  </td>
                  
                  <% str_submit = Time.use_zone(@time_zone) {event.created_D} %>
                  <% parse_submit = DateTime.parse(str_submit) %>
                  <td data-sort="<%= parse_submit.strftime("%Y%m%d%H%M%s") %>">
                    <%= link_to edit_events_path(event.id), class: "event_link" do %>
                      <time><%= str_submit %></time>
                    <% end %>
                  </td>

                  <td>
                    <div class="row">
                      <% if event.approved? %>
                        <div class="col-md-12 col-sm-12">
                          <span class="btn btn-success event_status" disabled data-toggle="tooltip" title="Already approved.">Approved</span>
                        </div>
                      <% elsif event.denied? %>
                        <div class="col-md-12 col-sm-12">
                          <span class="btn btn-danger event_status" disabled data-toggle="tooltip" title="Already denied.">Denied</span>
                        </div>
                      <% elsif event.canceled? %>
                        <div class="col-md-12 col-sm-12">
                          <span class="btn btn-warning event_status" disabled data-toggle="tooltip" title="Canceled">Canceled</span>
                        </div>
                      <% else %>
                        <div class="col-md-12 col-sm-12">
                          <span class="btn btn-default event_status" disabled data-toggle="tooltip" title="Pending">Pending</span>
                        </div>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="category-dashboard">
  <div class="page-title">
    <div class="title_left">
      <h3>Categories</h3>
    </div>
  </div>

  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-4 col-sm-5 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Add New Category</strong></h4>
          <%= form_tag new_category_path, {method: "get", class: "category_form"} do %>
            <div class="field">
              <label for="category_name">Name *</label>
              <input type="text" name="category_name" class="form-control" id="category_name" value="" placeholder="" required="required" />
            </div>
            <div class="field">
              <label for="category_description">Description</label>
              <textarea class="form-control" rows="4" id="category_description" name="category_description"></textarea>
            </div>
            <div class="field display-flex">
              <input type="checkbox" name="default_option" id="default_option" />
              <label for="default_option" class="default_label">Selectable for everyone?</label>
            </div>
            <%= submit_tag "Add New Category", class: "btn btn-primary add-category" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-md-8 col-sm-7 col-xs-12">
      <div class="x_panel">
        <div class="x_content">
          <h4><strong>Existing Categories</strong></h4>
          <table id="categoryTable" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Selectable for everyone?</th>
                <th>Count</th>
                <th colspan="1">Action</th>
              </tr>
            </thead>

            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <%= category.name %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <%= category.description %>
                    <% end %>
                  </td>
                  <td>
                    <%= link_to edit_category_path(category.slug), class: "category-link" do %>
                      <% if category.default_option? %>
                        <img src="<%= image_url('valid.png', alt: 'Yes') %>" class="category_icon" >
                      <% else %>
                        <img src="<%= image_url('invalid.png', alt: 'Yes') %>" class="category_icon" >
                      <% end %>
                    <% end %>
                  </td>
                  <td><%= category.event.count %></td>
                  <td>
                    <%= link_to 'Delete', category_path(category.slug), data: { confirm: 'Are you sure?' }, method: :delete %>
                  </td>
                </tr>
              <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>